#!/usr/bin/env python3
"""
Regenerate CLAUDE.md / AGENTS.md (the instructions the agent — Claude Code, Codex CLI, Gemini CLI… — reads every
turn) from the context managed on the board (/context: active groups and blocks) — `php artisan griglia:context
export` inside the container.

Usage:  scripts/sync-context.py            # write CLAUDE.md only if the content changed (exit 0)
        scripts/sync-context.py --check    # only report whether CLAUDE.md is in sync (exit 1 if not)
        scripts/sync-context.py --import   # the other way round: import the current CLAUDE.md into the board (--replace)
        scripts/sync-context.py --restore  # put the ORIGINAL files (docs/context-originals/) back in place of the generated ones
        scripts/sync-context.py --backup   # save the current non-generated files as originals
If the «Generate the instruction files from the board» switch is off in /context, the script restores the originals
and stops touching the files.

Made to run from cron too (every minute, silently): `* * * * * /path/to/laravel-dev/scripts/sync-context.py -q`.
The generated file carries an HTML-comment header: edit the blocks in /context, not the file.
"""
import os, re, subprocess, sys


def project_root():
    """Root of the project using the board: $GRIGLIA_PROJECT_ROOT, otherwise the directory holding these scripts
    (<project>/scripts, where `vendor:publish --tag=griglia-scripts` puts them) or — when the script is run straight
    from vendor/alle80/griglia/scripts — the directory holding `vendor`."""
    env = os.environ.get('GRIGLIA_PROJECT_ROOT')
    if env:
        return os.path.abspath(os.path.expanduser(env))
    here = os.path.dirname(os.path.abspath(__file__))
    parts = here.split(os.sep)
    if 'vendor' in parts:
        return os.sep.join(parts[:parts.index('vendor')]) or os.sep
    return os.path.dirname(here)


ROOT = project_root()
# Target files: one per agent family — CLAUDE.md (Claude Code), AGENTS.md (Codex CLI, Cursor, Jules, Amp, Zed…),
# GEMINI.md (Gemini CLI) — override with GRIGLIA_CONTEXT_TARGETS="CLAUDE.md,AGENTS.md,GEMINI.md"
TARGETS = [t.strip() for t in os.environ.get('GRIGLIA_CONTEXT_TARGETS', 'CLAUDE.md,AGENTS.md').split(',') if t.strip()]
TARGET = os.path.join(ROOT, TARGETS[0])
CONTAINER = os.environ.get('GRIGLIA_CONTAINER', 'laravel-dev-app')
GRIGLIA_USER = os.environ.get('GRIGLIA_USER', 'www-data')
# Artisan transport: 'docker' (default, `docker exec <container>`) or 'local' (PHP on the host, no Docker)
TRANSPORT = os.environ.get('GRIGLIA_TRANSPORT', 'docker')
PHP = os.environ.get('GRIGLIA_PHP', 'php')
HEADER = '<!-- Generated by Griglia (/context): edit the blocks there, not this file. -->\n'
# Any first line matching this is a header written by Griglia (older releases worded it differently, and the
# project can translate it): a file carrying one is generated, never a hand-written original.
GENERATED_RE = re.compile(r'^<!--[^\n]*Griglia \(/context\)[^\n]*-->\n')
# Originals (pre-board) of the generated files: saved here the first time a file is overwritten and put back
# with --restore or when «Generate the instruction files from the board» is switched off in /context
ORIGINALS = os.path.join(ROOT, 'docs', 'context-originals')


def artisan(*args, stdin=None):
    """`php artisan …` through `docker exec` (default) or — with GRIGLIA_TRANSPORT=local, for a Laravel running
    straight on the host, without Docker — with GRIGLIA_PHP from the project root."""
    if TRANSPORT == 'local':
        command, cwd = [PHP, 'artisan', *args], ROOT
    else:
        command, cwd = ['docker', 'exec', '-i', '-u', GRIGLIA_USER, CONTAINER, 'php', 'artisan', *args], None
    return subprocess.run(command, input=stdin, text=True, capture_output=True, cwd=cwd)


def is_generated(path):
    try:
        with open(path, encoding='utf-8') as fh:
            return bool(GENERATED_RE.match(fh.readline().rstrip('\n') + '\n'))
    except OSError:
        return False


def backup_original(name):
    """Save the original of <name> (only if it exists, is not generated and is not saved already)."""
    target = os.path.join(ROOT, name)
    dest = os.path.join(ORIGINALS, name)
    if os.path.isfile(target) and not is_generated(target) and not os.path.isfile(dest):
        os.makedirs(ORIGINALS, exist_ok=True)
        with open(target, encoding='utf-8') as src, open(dest, 'w', encoding='utf-8') as dst:
            dst.write(src.read())
        return True
    return False


def restore(quiet=False):
    """Put the originals back in place of the generated files (generated files without an original are removed)."""
    done = []
    for name in TARGETS:
        target = os.path.join(ROOT, name)
        orig = os.path.join(ORIGINALS, name)
        if os.path.isfile(orig):
            with open(orig, encoding='utf-8') as src:
                body = src.read()
            if not os.path.isfile(target) or open(target, encoding='utf-8').read() != body:
                with open(target, 'w', encoding='utf-8') as dst:
                    dst.write(body)
                done.append(name + ' (restored)')
        elif os.path.isfile(target) and is_generated(target):
            os.remove(target)
            done.append(name + ' (removed: no original)')
    if not quiet:
        print('originals restored: ' + (', '.join(done) if done else 'nothing to do'))


def sync_enabled():
    r = artisan('griglia:context', 'enabled')
    return r.returncode != 0 or r.stdout.strip() != '0'  # on error assume enabled (legacy package)


def main():
    quiet = '-q' in sys.argv
    if '--restore' in sys.argv:
        restore(quiet); return
    if '--backup' in sys.argv:
        print(', '.join(n for n in TARGETS if backup_original(n)) or 'nothing to back up'); return
    if not sync_enabled():
        # the board says «do not generate»: put the originals back (once) and leave the files alone
        restore(quiet=True); return
    if '--import' in sys.argv:
        md = open(TARGET, encoding='utf-8').read()
        head = GENERATED_RE.match(md)
        if head:
            md = md[head.end():]
        r = artisan('griglia:context', 'import', '--replace', stdin=md)
        print(r.stdout.strip() or r.stderr.strip()); sys.exit(r.returncode)
    r = artisan('griglia:context', 'export')
    if r.returncode != 0:
        if not quiet: print(r.stderr.strip() or 'export failed', file=sys.stderr)
        sys.exit(r.returncode)
    body = r.stdout
    if not body.strip():
        if not quiet: print('context is empty: CLAUDE.md left untouched', file=sys.stderr)
        sys.exit(2)
    new = HEADER + body
    changed = []
    for name in TARGETS:
        backup_original(name)
        target = os.path.join(ROOT, name)
        old = open(target, encoding='utf-8').read() if os.path.isfile(target) else ''
        if old != new:
            changed.append(name)
    if '--check' in sys.argv:
        print('in sync' if not changed else 'OUT OF SYNC: ' + ', '.join(changed)); sys.exit(0 if not changed else 1)
    if not changed:
        if not quiet: print(', '.join(TARGETS) + ' already up to date')
        return
    for name in changed:
        with open(os.path.join(ROOT, name), 'w', encoding='utf-8') as fh:
            fh.write(new)
    if not quiet: print(f'{", ".join(changed)} regenerated ({len(new)} chars)')


if __name__ == '__main__':
    main()
